-- Supabase schema for School Portal
-- Core tables for DAPO-sourced school data and sync tracking.

create table if not exists schools (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  npsn text not null unique,
  name text not null,
  short_name text,
  tagline text,
  status text,
  accreditation text,
  year_established text,
  address text,
  kode_pos text,
  kecamatan text,
  desa text,
  contact text,
  email text,
  hero_image text,
  card_image text,
  maps_embed text,
  sync_status text,
  profile_summary text,
  profile_details text[],
  facilities jsonb,
  grade_stats jsonb,
  total_students int,
  male_students int,
  female_students int,
  total_teachers int,
  total_classrooms int,
  total_study_groups int,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_sync_status (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  status text not null check (status in ('success', 'warning', 'failed')),
  message text,
  scraped_at timestamptz not null,
  source_url text,
  created_at timestamptz default now() not null
);

create table if not exists school_role_stats (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  role text not null check (role in ('guru', 'tenaga_didik', 'peserta_didik')),
  total int default 0,
  male int default 0,
  female int default 0,
  scraped_at timestamptz default now() not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Optional UI content tables. Use these if you want to migrate frontend hardcoded fields to DB.

create table if not exists school_principals (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  name text not null,
  position text,
  photo text,
  welcome text,
  nip text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_ui_contents (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  history text,
  vision text,
  mission text[],
  goals text[],
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_facilities_ui (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  name text not null,
  description text,
  photo text,
  icon text,
  count int,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_achievements (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  title text not null,
  year text,
  level text,
  description text,
  photo text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_news (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  title text not null,
  date text,
  excerpt text,
  thumbnail text,
  category text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_gallery (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  photo text not null,
  caption text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_staff (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  name text not null,
  position text,
  nip text,
  photo text,
  is_admin boolean default false,
  is_vice_principal boolean default false,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists school_teachers (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  name text not null,
  position text,
  nip text,
  photo text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);
